---
title: "ariel_summ_proj"
author: "Puvvula"
date: "2023-06-20"
output: pdf_document
---

```{r}
library(pacman)
pacman::p_load(tidyverse, janitor, reshape2, qgcomp, gridExtra)
path <- "~/Documents/PEACH_study/ariel_summ/"
```

#load and tidy variables
```{r}
dat<- read_csv(paste0(path, "ariel_exp_qn_full.csv")) |>
  select(c(2:13, 15:17, 19:22, 24:43, 142, 165, 251, 268, 291, 321, 
           starts_with("As_Urine_V1"), starts_with("Mo_Urine_V1"), 
           starts_with("Pb_Blood_V1"), starts_with("Mn_Blood_V1"), 
           starts_with("Mo_Blood_V1")))|>
  rename(bdi_v1="total_score", resil_v1 = "score_overall_resilience_mean", 
         bdi_v3="total_score_v3", resil_v3="score_overall_resili_v_36") |>
  mutate(race = case_when(
    pt_race___1 == "Checked" ~ "nhsp_black",
    pt_race___2 == "Checked" ~ "white",
    pt_race___3 == "Checked" ~ "asian",
    pt_race___4 == "Checked" ~ "latino",
    pt_race___5 == "Checked" ~ "native_havi",
    pt_race___6 == "Checked" ~ "ameri_ind",
    pt_race___777 == "Checked" ~ "other",
    pt_race___888 == "Checked" ~ "unkn",
    TRUE ~ "NA" )) |>
  mutate(race = if_else(race == "white", "white", "non-white")) |>
  mutate(pt_ethni = if_else(pt_ethni == "Hispanic / Latino", "hispanic", "non-hispanic")) |>
  mutate(pt_education = if_else(pt_education == "Bachelor's degree (e.g. BA, BS)" | 
                                  pt_education == "Master's degree (e.g. MA, MS, MEd)"| 
                                  pt_education == "Doctorate (e.g. PhD, EdD)", "bach-or-abv", "lt-bach")) |>
  mutate(household_income = case_when(
    household_income == "< $20,000" ~ "lt_80k",
    household_income == "$20,000-$39,999" ~ "lt_80k",
    household_income == "$40,000-$79,999" ~ "lt_80k",
    household_income == "$80,000-$119,999" ~ "abv_80k",
    household_income == "$120,000-$159,999" ~ "abv_80k",
    household_income == ">$160,000" ~ "abv_80k",
    TRUE ~ as.factor(household_income)  # Keep other values unchanged
    ))|>
  mutate(highway = if_else(highway == "More than 1 mile" , "gt_1mile", "lt_1mile")) |>
  mutate(bmi = (prepreg_weight * 0.453592) / (((height * 30.48 + height_2 * 2.54) / 100) ^ 2))  |>
  select(-c(3:12,18,27:34)) |>
  mutate_if(is.character, as.factor) |>
  mutate_if(is.numeric, ~round(., 2))
```

#summary table
```{r}
dat_tbl<- dat |> select(c("year_house", where(is.numeric)))

summ<- dat_tbl |>
  pivot_longer(!c(year_house), names_to = "chemical", values_to = "conc")|>
  group_by(chemical) |>
  summarize(count_na = sum(is.na(conc)),
            min_value = round(min(conc, na.rm=T),2),
            median_conc = round(median(conc, na.rm=T),2),
            percentile_25 = round(quantile(conc, 0.25, na.rm=T),2),
            percentile_75 = round(quantile(conc, 0.75, na.rm=T),2))
```

#imputing missing data with min
```{r}
#imputing missing values with minimum values
dat_imputed<- dat|>
  mutate(across(where(is.numeric), ~replace(., is.na(.), min(., na.rm = TRUE))))  |>
  mutate(highway= as.factor(if_else(is.na(highway), "lt_1mile", highway)),
         bluespace= as.factor(if_else(is.na(bluespace), "Rarely (< 1 time per month)", bluespace)),
         sex_infant= as.factor(if_else(is.na(sex_infant), "Male", sex_infant))
         )

write_csv(dat_imputed, paste0(path, "imputed_peach.csv"))
```


#correlation coefficients 
```{r}
dat_corr<- dat_imputed |> 
  select(where(is.numeric)) |>
  mutate_at(vars(11:15), ~log10(.+0.0000001)) |>
  rename_with(~ paste0("log_", .x), 11:15)

corr <- cor(dat_corr, method = "pearson", use = "complete.obs") |>
  melt()


ggplot(corr, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", 
                       midpoint = 0, breaks = seq(-1, 1, 0.2)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_text(colour = "black", size = 8),
        strip.text.x = element_text(colour = "black", size = 6.5),
        strip.text.y = element_text(colour = "black", size = 6.5)) +
  labs(title = "", x = "", y = "") +
  geom_text(aes(label = round(value, 2)), color = "black", size = 3)+
  guides(fill=FALSE)
```

#average levels during pregnancy vars 21-33
```{r}
dat_imputed<- read_csv(paste0(path, "imputed_peach.csv"))

dat_mod <- dat_imputed |>
  mutate(pss_avg = rowMeans(across(starts_with("pss14_")), na.rm = TRUE),
         bdi_avg = rowMeans(across(starts_with("bdi_")), na.rm = TRUE),
         resil_avg = rowMeans(across(starts_with("resil_")), na.rm = TRUE),
         pb_bld = rowMeans(across(starts_with("Pb_Blood")), na.rm = TRUE),
         mn_bld = rowMeans(across(starts_with("Mn_Blood")), na.rm = TRUE)) |>
  select(-c(21:28,31,32)) |>
  mutate(across(c(22, 23, 26:30), ~log10(.+0.0000001)))
```

#scatter plots with lm trend line with beta and p-value
```{r}
# List of x-variables
x_variables <- c("pss_avg", "bdi_avg", "resil_avg", "pb_bld")

# List of variables for y-axis
y_variables <- c("weight_infant", "length_infant", "ga_birth")

# List to store ggplot objects
plot_list <- list()

# create scatter plot of unique combination of x and y variables
for (x_var in x_variables) {
  for (y_var in y_variables) {
    plot <- ggplot(dat_mod, aes_string(x = x_var, y = y_var)) +
      geom_point(size = 2) +
      stat_smooth(method = "lm", se = TRUE, fullrange = TRUE, colour = "gray50")+
      theme_minimal()
    
    plot_list[[paste(x_var, y_var, sep = "_")]] <- plot
  }
}

# Combine the ggplot objects using grid.arrange
grid.arrange(grobs = plot_list, nrow = length(x_variables))
```

#qgcomp function
```{r}
qgcomp_func<- function(outcomes, dat, folder_path, mixture) {
  for(outcome in outcomes){
    formula <- as.formula(paste(outcome, "~ pss_avg+ bdi_avg+ resil_avg+ pb_bld+ mn_bld+ Pb_Urine_V1+ As_Urine_V1+ Mo_Urine_V1+ ","age + bmi+ sex_infant+ pt_education+ household_income+ race"))
       
        nb <- qgcomp.noboot(formula, expnms = mixture, data = dat, family= gaussian(), q=4)
        boot <- qgcomp.boot(formula, expnms = mixture, data = dat, family= gaussian(), q=4, B = 200, seed = 2022)
        save(nb, file = paste0(folder_path, "/", "nb_", outcome, ".rda"))
        save(boot, file = paste0(folder_path, "/", "boot_", outcome, ".rda"))
  }
}
```

#get results for metal and stress scale metrics as exposure mixture
```{r}
qgcomp_func(outcomes = c("weight_infant", "length_infant", "ga_birth"), 
            mixture = names(dat_mod[c(22,23,26:30)]),
            folder_path = path, 
            dat = dat_mod)
```

#manual extraction of results
```{r}
load(paste0(path, "nb_ga_birth.rda"))
load(paste0(path, "boot_ga_birth.rda"))

#only for files starts with nb_
nb
plot(nb)

#only for files starts with boot_
boot
plot(boot)
```


#Disparities regression model

```{r}
disparities_lm <- function(data, cat_vars, cont_vars) {
  result_df <- data.frame()  # initialize an empty dataframe for storing results

  for (cat_var in cat_vars) {
    for (cont_var in cont_vars) {
      # check if the continuous variable is numeric
      if (is.numeric(data[[cont_var]])) {
        # create a formula for linear regression including the specified variables
        formula <- as.formula(paste(cont_var, "~", cat_var, "+ pss_avg + bdi_avg + resil_avg + pb_bld + mn_bld + Pb_Urine_V1 + As_Urine_V1 + Mo_Urine_V1"))
        
        # fit the linear regression model
        lm_model <- lm(formula, data = data)
        
        # extract the relevant information from the linear regression model
        lm_coefficients <- summary(lm_model)$coefficients
        lm_beta <- lm_coefficients[2]
        lm_conf_int <- paste(round(confint(lm_model)[2, ], 2), collapse = " - ")
        lm_p_val<- summary(lm_model)$coefficient[2,"Pr(>|t|)"]
        
        # create a row for the result dataframe
        result_row <- data.frame(cat_var = cat_var,
                                 cont_var = cont_var,
                                 lm_beta = lm_beta,
                                 lm_conf_int = paste(lm_conf_int),
                                 lm_p_val= lm_p_val)
        # add the row to the result dataframe
        result_df <- rbind(result_df, result_row)
      } else {
        # if the continuous variable is not numeric, print a warning message
        warning(paste0("Variable '", cont_var, "' is not numeric and will be skipped."))
      }
    }
  }
  return(result_df)
}
```

```{r}
dat_mod <- dat_mod |>
  mutate_if(is.character, as.factor)

#re-level variables - reference categories
dat_mod$pt_education <- relevel(dat_mod$pt_education, ref = "bach-or-abv")
dat_mod$race <- relevel(dat_mod$race, ref = "white")
dat_mod$household_income <- relevel(dat_mod$household_income, ref = "abv_80k")


lm_res<- disparities_lm(data = dat_mod,
               cat_vars = c("race", "pt_education", "hous. ehold_income", "mold_mildew", "type_house", "year_house", 
                            "highway","stove","water", "moisture", "floors", "vacuum", "greenspace", "bluespace") ,
               cont_vars = c("weight_infant", "length_infant", "ga_birth"))

```

#practice
```{r}
lm_p<- lm(weight_infant~  race + pss_avg + bdi_avg + resil_avg + pb_bld + mn_bld + Pb_Urine_V1 + As_Urine_V1 + Mo_Urine_V1, 
          data = dat_mod)
summary(lm_p)

lm_p2<- lm(weight_infant~  race , 
          data = dat_mod)
```

