---
title: "colin"
author: "Puvvula"
date: "2023-04-27"
output: pdf_document
---

```{r}
library(pacman)
pacman::p_load(tidyverse, janitor)
path <- "~/Documents/PEACH_study/clem_raw_dat/"
```

```{r}
#load blood and urine data
blood<- read_csv(paste0(path, "blood_metal_conc.csv")) |> mutate(sample="blood")
urine<- read_csv(paste0(path, "urine_metal_conc.csv")) |> mutate(sample="urine")

#combine blood and urine data to a single dataframe
dat<- bind_rows(blood, urine)

#fix labels for the identifier matching
metal<- dat |>
  rename(label="obs")|>
  mutate(label = str_replace(label, 
                                 "(\\w)(\\s+)-(\\s+)(\\d)", 
                                 "\\1-\\4"),
         label = if_else(str_starts(label, "Urine-"), 
                         paste0("B5-", str_remove(label, "Urine-")), 
                         label),
         label = if_else(str_detect(label, "-[0-9]$"), 
                         str_replace(label, "-([0-9])$", "-0\\1"), 
                         label),
         label = str_replace(label, "\\s*-\\s*", "-"),
         label = if_else(label == "B5-50", "B6-01", label))
############################################################
#load linkage file
metal_linkage<- read_csv(paste0(path, "linkage_metals.csv"))|>
  select(c(1:4,8,9))
####################
#join id's from the sample submission IDs
metal_dat<- metal |> left_join(metal_linkage, by="label") |>
  clean_names()|>
  mutate(sample_type = if_else(sample_type == 
                                 "Whole Blood (EDTA)", 
                               "Whole Blood", sample_type)) |>
  mutate_if(is.character, as.factor)
#############################
#linkage with rita's data
rita_linkage<- read_csv(paste0(path, "linkage_rita.csv"))|>
  select(c(1,3)) |>
  rename(studyid="Ext Participant ID")|>
  distinct(Participant, studyid, .keep_all = TRUE) |>
  clean_names()|>
  mutate(studyid = str_remove(studyid, "^0+"))

#get study_id's and convert to wide format
metal_fin<- metal_dat |> left_join(rita_linkage, by="participant") |>
  select(c(2,3,7,8,10))|>
  clean_names() |>
  mutate(sample_type = if_else(sample_type == "Whole Blood","Blood", 
                               sample_type))|>
  unite(variable, metal, sample_type, visit, sep = "_", remove = FALSE)|>
  select(c(1,2,6))

metal_fin_wide<- metal_fin |>
  pivot_wider(names_from = variable, values_from = cal_conc)

write_csv(metal_fin_wide, paste0(path, "ariel_metal_wide.csv"))
```

#questionnaire data
```{r}
qn_dat<- read_csv(paste0(path, "analysis_colin.csv"))
qn_dat$studyid<- as.character(qn_dat$studyid)

dat_qn_met<- full_join(qn_dat, metal_fin_wide, by="studyid")


write_csv(dat_qn_met, paste0(path, "ariel_dat_qn_met.csv"))
```

############################################
```{r}
dat<- read_csv(paste0(path, "colin_dat_qn_met.csv"))
```

#########################
```{r}
library(pacman)

pacman::p_load(tidyverse, janitor, haven, skimr, readr, reshape2, kableExtra, gridExtra)
path <- "~/Documents/PEACH_study/dep_scale/"
```

```{r}
dat_existing<- read_csv(paste0(path, "ariel_dat_qn_met.csv")) 
dat<- read_csv(paste0(path, "analysis_ariel.csv")) 

dat_with_dep_score<- left_join(dat_existing, dat, by="studyid")

write_csv(dat_with_dep_score, "~/Documents/PEACH_study/clem_raw_dat/ariel_exp_qn_full.csv")
```

```{r}
dat<- read_csv("~/Documents/PEACH_study/clem_raw_dat/ariel_exp_qn_full.csv") |>
  mutate(race = case_when(
    pt_race___1 == "Checked" ~ "nhsp_black",
    pt_race___2 == "Checked" ~ "white",
    pt_race___3 == "Checked" ~ "asian",
    pt_race___4 == "Checked" ~ "latino",
    pt_race___5 == "Checked" ~ "native_havi",
    pt_race___6 == "Checked" ~ "ameri_ind",
    pt_race___777 == "Checked" ~ "other",
    pt_race___888 == "Checked" ~ "unkn",
    TRUE ~ "NA" )) |>
  mutate_if(is.character, as.factor)
    
```



