---
title: "icpms_metals_urine"
author: "Puvvula"
date: "2023-04-27"
output: pdf_document
---

```{r}
library(pacman)
pacman::p_load(tidyverse, janitor)
path <- "/Users/jpuvvula/Documents/PEACH_study/clem_raw_dat/"
```

#FOR BLOOD
```{r}
variables_to_divide <- c("Be", "B", "Na", "Mg", "Al", "Si", "K", "Ca", "Ti", "V", "Cr", "Mn", "Fe", 
                         "Co", "Ni", "Cu","Zn", "As", "Se", "Sr", "Mo", "Ag", "Cd", "Sn", "Sb", 
                         "Ba", "Tl", "Pb")


raw<- read_csv(paste0(path, "blood_met_work.csv")) |> 
  rename_all(~gsub("^\\d+([^0-9])", "\\1", .)) |>
  mutate(across(all_of(variables_to_divide), ~ round(./Tb, 6))) |>
  select(-c(Tb))


#Data formatting - linear calibration model - blood
lm_calib <- raw|> filter(!is.na(conc)) |>
  pivot_longer(!c(id, conc), names_to = "metal", values_to = "elem_ist_rat")

#Data formatting - predicting concentrations - blood
pred_conc <- raw|> filter(startsWith(id, "B7") | startsWith(id, "B8")) |>
  pivot_longer(!c(id, conc), names_to = "metal", values_to = "elem_ist_rat")
  
```

#FOR URINE
```{r}
variables_to_divide <- c("Be", "B", "Na", "Mg", "Al", "Si", "K", "Ca", "Ti", "V", "Cr", "Mn", "Fe", 
                         "Co", "Ni", "Cu","Zn", "As", "Se", "Sr", "Mo", "Ag", "Cd", "Sn", "Sb", 
                         "Ba", "Tl", "Pb")


raw<- read_csv(paste0(path, "urine_met_work.csv")) |> 
  rename_all(~gsub("^\\d+([^0-9])", "\\1", .)) |>
  mutate(across(all_of(variables_to_divide), ~ round(./Tb, 6))) |>
  select(-c(Tb))


#Data formatting - linear calibration model - blood
lm_calib <- raw|> filter(!is.na(conc)) |>
  select(-c(sample)) |>
  pivot_longer(!c(id, conc), names_to = "metal", values_to = "elem_ist_rat")

#Data formatting - predicting concentrations - blood
pred_conc <- raw|> 
  select(-c(sample)) |>
  filter(startsWith(id, "Urine")) |>
  pivot_longer(!c(id, conc), names_to = "metal", values_to = "elem_ist_rat")
  
```

################################################################################

```{r}
# Define function to build linear models for each unique value of the 'metal' variable
lm_metals <- function(data) {
  # Create an empty data frame to store results
  results <- data.frame(metal = character(),
                        intercept = numeric(),
                        estimate = numeric(),
                        r_squared = numeric(),
                        stringsAsFactors = FALSE)
  
  # Get unique values of the 'metal' variable
  unique_metals <- unique(data$metal)
  
  # Loop through each unique value of the 'metal' variable
  for (i in seq_along(unique_metals)) {
    # Extract data for the current metal
    metal_data <- subset(data, metal == unique_metals[i])
    
    # Build linear model for the current metal
    lm_fit <- lm(elem_ist_rat ~ conc, data = metal_data)
    
    # Extract intercept, coefficient, and R-squared value and round to 2 decimal places
    intercept <- round(coef(lm_fit)[1], 4)
    estimate <- round(coef(lm_fit)[2], 4)
    r_squared <- round(summary(lm_fit)$r.squared, 4)
    
    # Add results to data frame
    results[i, ] <- c(unique_metals[i], intercept, estimate, r_squared)
  }
  
  # Return results
  return(results)
}

```

```{r}
results <- lm_metals(lm_calib) |>
  mutate_at(vars(2:4), ~ as.numeric(.))
```

```{r}
ggplot(lm_calib, aes(x = elem_ist_rat, y = conc))  +
  labs(x="Element/ISTD  Area RATIO", 
       y="Calculated conc (from cal curve)")+
  facet_wrap(~ metal, scales = "free") +
  stat_smooth(method = "lm", se = T, fullrange = TRUE, colour="gray")+
  geom_point()+
  theme_minimal()
```

===================================================
```{r}
pred_conc_res <- pred_conc |> 
  left_join(results, by = "metal") |>
  mutate(conc = as.numeric(if_else(is.na(intercept) | is.na(estimate), 
                                              NA_real_, 
                                              (elem_ist_rat - intercept) / estimate)*10)) |>
  mutate(conc = ifelse(conc < 0, 0, conc))|>
  select(-c(intercept, estimate, r_squared, elem_ist_rat))

write_csv(pred_conc_res, paste0(path, "urine_metal_conc.csv"))
```


#summary table
```{r}
summary_table <- pred_conc_res %>%
  group_by(metal) %>%
  summarize(
    average = round(mean(conc), 2),
    min_conc = round(min(conc), 2),
    max_conc = round(max(conc), 2),
    median_conc = round(median(conc), 2),
    q1_conc = round(quantile(conc, probs = 0.25), 2),
    q3_conc = round(quantile(conc, probs = 0.75), 2))

#histograms
ggplot(pred_conc_res, aes(x = conc)) +
    geom_histogram( color = "black", fill = "white") +
    facet_wrap(~metal, scales = "free") +
    labs(x = "conc", y = "Frequency") +
    theme_bw()+
  labs(x="urine metal concentration in PPB",
       y="frequency")
```



